eureka:
  client:
    service-url:
      # 将服务注册到 Eureka Serve 上
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud?characterEncoding=utf-8&useSSL=false
  application:
    name: product
  jpa:
    show-sql: true
